language: ruby

dist: trusty

env:
  - CI=true

rvm:
  - 1.8
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head

jobs:
  allow_failures:
    - rvm: 3.0
    - rvm: ruby-head
